1- Import the numpy package under the name np

In [2]:
import numpy as np

2- Create a null vector of size 10


In [2]:
x =np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
3- Create a vector with values ranging from 10 to 49

In [4]:
vrange= np.arange(10,49)
print(vrange) 


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
(39,)


In [7]:
4- Find the shape of previous array in question 3

(39,)


In [ ]:
print(vrange.shape)

5- Find the shape of previous array in question 3

In [8]:
arrType = vrange.dtype
print(arrType)

int32


In [ ]:
6- Print the numpy version and the configuration

In [11]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


In [ ]:
7- Print the dimension of the array in question 3

In [12]:
arr_dim = vrange.ndim
print(arr_dim)

1


In [22]:
array = [True]
bool_arr = np.random.choice(array, size=10)
print(bool_arr)


[ True  True  True  True  True  True  True  True  True  True]


8- Create a two dimensional array

In [4]:
m = int(input("Enter row size:"))
n = int(input("Enter column size:"))

two_dim_arr = np.ndarray(shape=(m,n) , dtype=int)
print(two_dim_arr.ndim)

Enter row size:3
Enter column size:5
2


In [ ]:
9- Create a three dimensional array

In [6]:
m = int(input("Enter row size:"))
n = int(input("Enter column size:"))
z = int(input("Enter row size:"))

three_dim_arr = np.ndarray(shape=(m,n,z), dtype= int)
print(three_dim_arr.ndim)

Enter row size:4
Enter column size:5
Enter row size:3
3


In [ ]:
10- Reverse a vector (first element becomes last)

In [1]:
import nump
print("Original array:")
print(x)y as np
x = np.arange(1, 50)
print("Reverse array:")
x = x[::-1]
print(x)



Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
Reverse array:
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1]


In [ ]:
11- Create a null vector of size 10 but the fifth value which is 1

In [3]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
12- Create a 3x3 identity matrix

In [4]:
array_Identity = np.identity(3)
print(array_Identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
13- arr = np.array([1, 2, 3, 4, 5
                    
Convert the data type of the given array from int to float

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr= arr.astype('float64')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [ ]:
14- arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

Multiply arr1 with arr2

In [6]:
 arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [ ]:
15- arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [11]:
arr1= np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

comparison = arr1 == arr2 
equal_arrays = comparison.all() 
  
print(equal_arrays) 
    

False


In [ ]:
16-Extract all odd numbers from arr with values(0-9)

In [33]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
odd_arr = []

for i in x:
    if i % 2 !=0:
        odd_arr.append(i)
print(np.array(odd_arr))

[1 3 5 7 9]


In [ ]:
17- replace all odd numbers to -1 from previous array

In [35]:
print(x)
x[odd_arr] = -1
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
18- arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [38]:
arr = np.arange(10)
print(arr)
arr[5:9] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]


In [ ]:
19- Create a 2d array with 1 on the border and 0 inside

In [46]:
arr_onezero = np.ones((7,7))
print(arr_onezero)

arr_onezero[1:-1, 1:-1]= 0
print(arr_onezero)


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
Difficulty Level Medium

In [ ]:
20- 
Difficulty Level Medium

arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [48]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
print(arr2d)
arr2d[1,1] = 12
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


In [ ]:
21- arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [61]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
arr3d[0,0] = 64
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
22- Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [63]:
arr2d = np.array([[0, 1, 2],
                  [3, 4, 5], 
                  [6, 7, 8,]])
print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
23- Create a 10x10 array with random values and find the minimum and maximum values

In [73]:
import numpy as np

arr10 = np.random.randint(100, size=(10,10))
print(arr10)


[[72 21 77 46 94 70 82 35 43 84]
 [64 79 86 66 59 35 27 40 83 54]
 [92  2 61 28 44 52 61 55 26 25]
 [61  2 19 53 50 76 69  3 40 33]
 [ 2 97 93 48  1 39 54 25 30  5]
 [63 45 51 33 15  4 32 77  1 21]
 [81 65 86 49 80 82 71 12 72 75]
 [13 99  6 40 88 71 45  9 40 35]
 [85 76 56  0 54 99 40 78 76 19]
 [60 80 54 79 45 32 19 89 14 50]]


In [ ]:
24. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b

In [74]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b)
print('common val', c)

common val [2 4]


In [ ]:
25- a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [7]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_indexes = np.searchsorted(a, np.intersect1d(a,b))
print(common_indexes)
    

[1 5]


In [ ]:
26- names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [23]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
namesi = np.where(names != "Will")
print()
print(data[namesi])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.79307894 -0.80554308  1.00620655  0.57519177]
 [-0.77652413 -0.38446271  0.52585825 -2.26131391]
 [ 0.21626991 -0.99142399 -0.322666    1.23525549]
 [ 1.48433145 -1.41974541  0.65021449 -0.29683001]
 [-2.44711238  0.88363772 -0.94032306 -0.12382848]
 [-0.05627252 -2.24482234 -2.50683653  0.12570266]
 [ 1.19039069 -0.02029973 -0.41933694 -0.37256697]]

[[ 0.79307894 -0.80554308  1.00620655  0.57519177]
 [-0.77652413 -0.38446271  0.52585825 -2.26131391]
 [ 1.48433145 -1.41974541  0.65021449 -0.29683001]
 [-0.05627252 -2.24482234 -2.50683653  0.12570266]
 [ 1.19039069 -0.02029973 -0.41933694 -0.37256697]]


In [ ]:
27- names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

In [36]:
names2 = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
nameswj = (np.where(names2 != "Will") and (names2 != "Joe"))
print()
print(data[nameswj])


[[-0.38666606  0.05430733 -0.81530044 -0.97663823]
 [ 1.77437656 -0.30380431 -1.72783175 -0.25783694]
 [-1.7543357  -0.87342167 -0.08484586 -0.03936911]
 [ 0.72288665 -0.25575744 -0.60758307 -1.29755389]
 [ 1.1188558  -0.59218511 -0.01920042  0.78699618]
 [-0.5123073   0.03352541  0.86876345 -0.1434202 ]
 [-0.00294056  0.39112093  1.81580705 -1.56322609]]

[[-0.38666606  0.05430733 -0.81530044 -0.97663823]
 [-1.7543357  -0.87342167 -0.08484586 -0.03936911]
 [ 0.72288665 -0.25575744 -0.60758307 -1.29755389]
 [ 1.1188558  -0.59218511 -0.01920042  0.78699618]]


In [ ]:
Difficulty Level Hard

28- Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [37]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[ 7.35407674 10.90299889  5.41135839]
 [14.46838879  9.18945462 11.02135931]
 [ 6.11499987  8.76246804  1.38193433]
 [12.4822776   3.44637171  9.93568188]
 [ 3.79495669  2.71966928 13.76505265]]


In [ ]:
29- Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [39]:
rand_arr1 = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr1)

[[[ 8.02178286  6.99713938  6.21823796  8.09431276]
  [ 2.6072349   8.89542761  4.54194519  2.40158067]]

 [[ 4.83158211  7.33808249 15.65744664  1.95443903]
  [13.19881896  9.79482596  5.05796615 10.06927066]]]


In [ ]:
Swap axes of the array you created in Question 32

In [40]:
swaparr = np.swapaxes(rand_arr1,0,2)
print(swaparr)

[[[ 8.02178286  4.83158211]
  [ 2.6072349  13.19881896]]

 [[ 6.99713938  7.33808249]
  [ 8.89542761  9.79482596]]

 [[ 6.21823796 15.65744664]
  [ 4.54194519  5.05796615]]

 [[ 8.09431276  1.95443903]
  [ 2.40158067 10.06927066]]]


In [ ]:
Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [69]:
arr= np.sqrt(np.random.randn(10))
print(arr)
arr_replace = np.nan_to_num(arr)
print(arr_replace)



[0.16846187 0.80438655        nan 0.2711152         nan 0.99893024
 0.43019302 1.01712701 1.35913811        nan]
[0.16846187 0.80438655 0.         0.2711152  0.         0.99893024
 0.43019302 1.01712701 1.35913811 0.        ]


<ipython-input-69-2f30e0f3f45f>:1: RuntimeWarning: invalid value encountered in sqrt
  arr= np.sqrt(np.random.randn(10))


In [ ]:
Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0


In [73]:
a1 = np.random.randn(12)
a2 = np.random.randn(12)

print(a1)
print(a2)
print()
c= np.maximum(a1,a2)
print(c)

[-0.31017133 -1.39693453  0.06293791 -0.80669458 -0.12021919 -0.73596089
 -0.29395478 -1.16656324 -0.98790731  0.40754102 -0.72998058  0.00641566]
[ 2.06534817 -0.14697714 -1.17846084 -0.7502129  -1.21098522 -0.47232424
  0.93108054  0.90607084 -0.95440905 -0.55377507 -0.50645376 -2.08341191]

[ 2.06534817 -0.14697714  0.06293791 -0.7502129  -0.12021919 -0.47232424
  0.93108054  0.90607084 -0.95440905  0.40754102 -0.50645376  0.00641566]


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [77]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
_, idx= np.unique(names, return_index =True)
print(names[np.sort(idx)])


['Bob' 'Joe' 'Will']


In [ ]:
a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [81]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c= np.setdiff1d(a, b)
print(c)

[1 2 3 4]


In [ ]:
Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [87]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])


sampleArray = np.delete(sampleArray , 1, axis = 1) 
print("After deleting col")
print (sampleArray)


newColumn = np.array([[10,10,10]])

sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print("Array after inserting column 2 on axis 1")
print(sampleArray)



After deleting col
[[34 73]
 [82 12]
 [53 66]]


ValueError: could not broadcast input array from shape (10,1) into shape (3,1)

In [90]:

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [91]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])


c = np.dot(x,y)

print(c)

[[ 28.  64.]
 [ 67. 181.]]


In [ ]:
Generate a matrix of 20 random values and find its cumulative sum

In [97]:
a = np.random.rand(20)
print(a)
sumc= np.cumsum(a)
print("cumulative sum is:")
print(sumc)

[0.94576164 0.81684885 0.14107723 0.18511014 0.76716609 0.50371386
 0.40408022 0.88520453 0.69387704 0.29309957 0.22474308 0.60924938
 0.96553683 0.26695968 0.73954818 0.38545354 0.47497038 0.73886962
 0.72434995 0.95826226]
cumulative sum is:
[ 0.94576164  1.76261049  1.90368772  2.08879786  2.85596395  3.35967782
  3.76375803  4.64896256  5.34283959  5.63593917  5.86068224  6.46993162
  7.43546845  7.70242813  8.44197632  8.82742986  9.30240023 10.04126985
 10.7656198  11.72388206]
